services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "6868:8080"
    networks:
      - my-network-name

    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d7fhnlpkh4rs739peshg-a.oregon-postgres.render.com:5432/ECOTRACKG5
      - SPRING_DATASOURCE_USERNAME=andre
      - SPRING_DATASOURCE_PASSWORD=9ZCLRuxI9MJnVCKITxbcxPLlgiIQGuih
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  my-network-name:
    name: springcloud