spring.application.name=TP-Grupo5-Ecotrack-Backend

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://dpg-d7fhnlpkh4rs739peshg-a.oregon-postgres.render.com:5432/ECOTRACKG5
spring.datasource.username=andre
spring.datasource.password=9ZCLRuxI9MJnVCKITxbcxPLlgiIQGuih

# Activa/desactiva la UI de Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


ip.frontend=http://localhost:4200

jwt.secret=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==

